name = "persistia-local-b"
main = "src/index.ts"
compatibility_date = "2026-03-01"
compatibility_flags = ["nodejs_compat"]

[[rules]]
type = "Text"
globs = ["**/*.html"]

[[durable_objects.bindings]]
name = "PERSISTIA_WORLD"
class_name = "PersistiaWorldV4"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["PersistiaWorldV4"]

[vars]
NODE_URL = "http://localhost:8789"
SEED_NODES = "https://persistia.carnation-903.workers.dev/?shard=node-1,https://persistia.carnation-903.workers.dev/?shard=node-2,https://persistia.carnation-903.workers.dev/?shard=node-3"
